import { DifficultyLevel, QuestionType, Question } from '../../../types';

// Helper function to generate unique IDs
const generateId = (() => {
  let counter = 500; // Start from 500 to avoid ID conflicts
  return () => (counter++).toString();
})();

// Additional questions by difficulty level
export const additionalEasyQuestions: Question[] = [
  // Easy questions - Math
  {
    _id: generateId(),
    content: 'What is 12 + 8?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['18', '19', '20', '21'],
    correctAnswer: '20',
    explanation: '12 + 8 = 20',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['addition', 'arithmetic'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 15 - 7?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['7', '8', '9', '10'],
    correctAnswer: '8',
    explanation: '15 - 7 = 8',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['subtraction', 'arithmetic'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 4 × 3?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['7', '10', '12', '15'],
    correctAnswer: '12',
    explanation: '4 × 3 = 12',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['multiplication', 'arithmetic'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 10 ÷ 2?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['2', '4', '5', '6'],
    correctAnswer: '5',
    explanation: '10 ÷ 2 = 5',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['division', 'arithmetic'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the next number in the sequence: 2, 4, 6, 8, ...?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['9', '10', '11', '12'],
    correctAnswer: '10',
    explanation: 'This is a sequence of even numbers, increasing by 2 each time. After 8 comes 10.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['patterns', 'sequences'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // Easy questions - Science
  {
    _id: generateId(),
    content: 'Which of these is a mammal?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Fish', 'Snake', 'Dolphin', 'Lizard'],
    correctAnswer: 'Dolphin',
    explanation: 'Dolphins are mammals. They breathe air, give birth to live young, and feed their babies milk.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['animals', 'classification'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What do plants need to make their own food?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Only water', 'Only sunlight', 'Water, sunlight, and air', 'Only soil'],
    correctAnswer: 'Water, sunlight, and air',
    explanation: 'Plants make their own food through photosynthesis, which requires water, sunlight, and carbon dioxide from the air.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['plants', 'photosynthesis'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which planet is closest to the Sun?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Earth', 'Venus', 'Mars', 'Mercury'],
    correctAnswer: 'Mercury',
    explanation: 'Mercury is the closest planet to the Sun in our solar system.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['astronomy', 'solar system'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the main function of the lungs?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Pump blood', 'Digest food', 'Filter waste', 'Take in oxygen'],
    correctAnswer: 'Take in oxygen',
    explanation: 'The main function of the lungs is to take in oxygen from the air and release carbon dioxide.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['human body', 'respiratory system'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is a source of light?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Moon', 'Mirror', 'Flashlight', 'Window'],
    correctAnswer: 'Flashlight',
    explanation: 'A flashlight produces its own light. The Moon reflects light from the Sun, and mirrors and windows reflect or transmit light from other sources.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['light', 'energy'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // Easy questions - English
  {
    _id: generateId(),
    content: 'Which word is a noun in the sentence: "The happy dog ran quickly"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['happy', 'dog', 'ran', 'quickly'],
    correctAnswer: 'dog',
    explanation: 'A noun is a person, place, thing, or idea. In this sentence, "dog" is a thing, so it is a noun.',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['grammar', 'parts of speech'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is a complete sentence?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['The big dog.', 'Running fast.', 'She sings.', 'Under the table.'],
    correctAnswer: 'She sings.',
    explanation: 'A complete sentence needs a subject and a verb. "She sings" has both: "She" (subject) and "sings" (verb).',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['grammar', 'sentences'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which word is spelled correctly?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['beleive', 'recieve', 'achieve', 'freind'],
    correctAnswer: 'achieve',
    explanation: 'The correct spelling is "achieve". The other words should be spelled "believe", "receive", and "friend".',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['spelling', 'vocabulary'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the past tense of "run"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['run', 'running', 'ran', 'runned'],
    correctAnswer: 'ran',
    explanation: 'The past tense of "run" is "ran". This is an irregular verb that doesn\'t follow the pattern of adding "-ed".',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['grammar', 'verbs'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which punctuation mark ends a question?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Period (.)', 'Question mark (?)', 'Exclamation point (!)', 'Comma (,)'],
    correctAnswer: 'Question mark (?)',
    explanation: 'A question mark (?) is used at the end of a sentence that asks a question.',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['punctuation', 'grammar'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // More easy questions - Math
  {
    _id: generateId(),
    content: 'What is half of 18?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['6', '8', '9', '10'],
    correctAnswer: '9',
    explanation: 'Half of 18 is 18 ÷ 2 = 9.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['division', 'fractions'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'How many sides does a pentagon have?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['3', '4', '5', '6'],
    correctAnswer: '5',
    explanation: 'A pentagon has 5 sides. The prefix "penta-" means five.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['geometry', 'shapes'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 5 × 5?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['20', '25', '30', '35'],
    correctAnswer: '25',
    explanation: '5 × 5 = 25',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['multiplication', 'arithmetic'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which number is greater: 0.8 or 0.75?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['0.75', '0.8', 'They are equal', 'Cannot be determined'],
    correctAnswer: '0.8',
    explanation: '0.8 = 0.80, which is greater than 0.75.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['decimals', 'comparison'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of 7 + 3 × 2?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['13', '20', '14', '10'],
    correctAnswer: '13',
    explanation: 'Following the order of operations (PEMDAS), multiplication comes before addition. So 7 + 3 × 2 = 7 + 6 = 13.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['order of operations', 'arithmetic'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

export const additionalMediumQuestions: Question[] = [
  // Medium questions - Math
  {
    _id: generateId(),
    content: 'What is the value of 3² + 4²?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['7', '25', '49', '81'],
    correctAnswer: '25',
    explanation: '3² + 4² = 9 + 16 = 25',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['exponents', 'arithmetic'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Solve for x: 2x + 5 = 15',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['5', '7', '10', '20'],
    correctAnswer: '5',
    explanation: '2x + 5 = 15\n2x = 10\nx = 5',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['algebra', 'equations'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the area of a rectangle with length 8 cm and width 6 cm?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['14 cm²', '28 cm²', '48 cm²', '64 cm²'],
    correctAnswer: '48 cm²',
    explanation: 'The area of a rectangle is length × width = 8 cm × 6 cm = 48 cm².',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['geometry', 'area'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 25% of 80?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['15', '20', '25', '40'],
    correctAnswer: '20',
    explanation: '25% of 80 = 0.25 × 80 = 20',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['percentages', 'arithmetic'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of 2³ × 2²?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['25', '32', '64', '128'],
    correctAnswer: '32',
    explanation: '2³ × 2² = 8 × 4 = 32. Alternatively, using the laws of exponents: 2³ × 2² = 2³⁺² = 2⁵ = 32.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['exponents', 'arithmetic'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // Medium questions - Science
  {
    _id: generateId(),
    content: 'Which of these is NOT a renewable energy source?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Solar', 'Wind', 'Natural gas', 'Hydroelectric'],
    correctAnswer: 'Natural gas',
    explanation: 'Natural gas is a fossil fuel and is not renewable. Solar, wind, and hydroelectric are all renewable energy sources.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['energy', 'environment'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the process by which water changes from a liquid to a gas?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Condensation', 'Evaporation', 'Precipitation', 'Sublimation'],
    correctAnswer: 'Evaporation',
    explanation: 'Evaporation is the process by which water changes from a liquid to a gas or vapor.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['water cycle', 'states of matter'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these organs is part of the digestive system?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Lungs', 'Heart', 'Kidneys', 'Stomach'],
    correctAnswer: 'Stomach',
    explanation: 'The stomach is part of the digestive system. It breaks down food and mixes it with digestive juices.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['human body', 'digestive system'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the chemical formula for water?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['H₂O', 'CO₂', 'O₂', 'NaCl'],
    correctAnswer: 'H₂O',
    explanation: 'The chemical formula for water is H₂O, which means each water molecule consists of two hydrogen atoms and one oxygen atom.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['chemistry', 'compounds'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is an example of a physical change?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Burning wood', 'Rusting iron', 'Melting ice', 'Cooking an egg'],
    correctAnswer: 'Melting ice',
    explanation: 'Melting ice is a physical change because the water only changes state from solid to liquid; it doesn\'t change its chemical composition.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['chemistry', 'physical changes'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // Medium questions - English
  {
    _id: generateId(),
    content: 'Which of these is a compound sentence?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'The dog barked loudly.',
      'The dog barked loudly, and the cat ran away.',
      'The dog, which was large and brown, barked loudly.',
      'Because the dog barked loudly, the cat ran away.'
    ],
    correctAnswer: 'The dog barked loudly, and the cat ran away.',
    explanation: 'A compound sentence contains two independent clauses joined by a conjunction. "The dog barked loudly" and "the cat ran away" are both independent clauses joined by "and".',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['grammar', 'sentences'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which word is an adverb in the sentence: "She quickly solved the difficult problem"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['She', 'quickly', 'difficult', 'problem'],
    correctAnswer: 'quickly',
    explanation: 'An adverb modifies a verb, adjective, or another adverb. In this sentence, "quickly" modifies the verb "solved", telling how she solved the problem.',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['grammar', 'parts of speech'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the meaning of the idiom "break a leg"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['To actually break your leg', 'To run very fast', 'Good luck', 'To make a mistake'],
    correctAnswer: 'Good luck',
    explanation: '"Break a leg" is an idiom that means "good luck", often used in theater before a performance.',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['vocabulary', 'idioms'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is a simile?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'The stars are diamonds in the sky.',
      'She is as busy as a bee.',
      'The wind whispered through the trees.',
      'The old man was a walking dictionary.'
    ],
    correctAnswer: 'She is as busy as a bee.',
    explanation: 'A simile is a figure of speech that compares two unlike things using "like" or "as". "She is as busy as a bee" compares a person to a bee using "as".',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['literature', 'figurative language'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the correct way to write the possessive form of "children"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['childrens', 'childrens\'', 'children\'s', 'childrenses'],
    correctAnswer: 'children\'s',
    explanation: 'To form the possessive of a plural noun that doesn\'t end in "s" (like "children"), add an apostrophe followed by "s".',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['grammar', 'possessives'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // More medium questions - Math
  {
    _id: generateId(),
    content: 'What is the value of x in the equation 3x - 7 = 14?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['5', '7', '9', '21'],
    correctAnswer: '7',
    explanation: '3x - 7 = 14\n3x = 21\nx = 7',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['algebra', 'equations'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the perimeter of a square with side length 6 cm?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['12 cm', '18 cm', '24 cm', '36 cm'],
    correctAnswer: '24 cm',
    explanation: 'The perimeter of a square is 4 × side length = 4 × 6 cm = 24 cm.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['geometry', 'perimeter'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of 2/3 + 1/4?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['3/7', '7/12', '11/12', '3/12'],
    correctAnswer: '11/12',
    explanation: 'To add fractions with different denominators, we need to find a common denominator. The least common multiple of 3 and 4 is 12.\n2/3 = 8/12\n1/4 = 3/12\n8/12 + 3/12 = 11/12',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['fractions', 'addition'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'If a car travels at 60 miles per hour, how far will it travel in 2.5 hours?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['120 miles', '150 miles', '180 miles', '200 miles'],
    correctAnswer: '150 miles',
    explanation: 'Distance = Speed × Time = 60 miles per hour × 2.5 hours = 150 miles',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['word problems', 'rate'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of 0.25 × 16?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['0.4', '4', '40', '400'],
    correctAnswer: '4',
    explanation: '0.25 × 16 = 1/4 × 16 = 16/4 = 4',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['decimals', 'multiplication'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  }
];

export const additionalHardQuestions: Question[] = [
  // Hard questions - Math
  {
    _id: generateId(),
    content: 'Solve the quadratic equation: x² - 5x + 6 = 0',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['x = 2, x = 3', 'x = -2, x = -3', 'x = 2, x = -3', 'x = -2, x = 3'],
    correctAnswer: 'x = 2, x = 3',
    explanation: 'To solve x² - 5x + 6 = 0, we can factor: (x - 2)(x - 3) = 0. So either x - 2 = 0 or x - 3 = 0, which gives us x = 2 or x = 3.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['algebra', 'quadratic equations'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the derivative of f(x) = 3x² - 2x + 1?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['f\'(x) = 6x - 2', 'f\'(x) = 3x² - 2', 'f\'(x) = 6x² - 2x', 'f\'(x) = 6x - 2x'],
    correctAnswer: 'f\'(x) = 6x - 2',
    explanation: 'To find the derivative, we use the power rule: d/dx(x^n) = n·x^(n-1). So, d/dx(3x²) = 3·2·x^(2-1) = 6x, d/dx(-2x) = -2, and d/dx(1) = 0. Adding these together: f\'(x) = 6x - 2 + 0 = 6x - 2.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['calculus', 'derivatives'],
    grade: '11',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of sin(30°)?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['1/4', '1/3', '1/2', '√3/2'],
    correctAnswer: '1/2',
    explanation: 'The sine of 30° (or π/6 radians) is 1/2. This is one of the standard trigonometric values.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['trigonometry', 'angles'],
    grade: '10',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the equation of a circle with center (2, -3) and radius 4?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      '(x - 2)² + (y + 3)² = 16',
      '(x - 2)² + (y - 3)² = 16',
      '(x + 2)² + (y - 3)² = 16',
      '(x + 2)² + (y + 3)² = 16'
    ],
    correctAnswer: '(x - 2)² + (y + 3)² = 16',
    explanation: 'The equation of a circle with center (h, k) and radius r is (x - h)² + (y - k)² = r². With center (2, -3) and radius 4, we get (x - 2)² + (y - (-3))² = 4², which simplifies to (x - 2)² + (y + 3)² = 16.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['geometry', 'circles'],
    grade: '10',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of log₃(27)?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['1', '2', '3', '9'],
    correctAnswer: '3',
    explanation: 'log₃(27) = log₃(3³) = 3. This is because if log₃(x) = y, then 3^y = x. Here, 3³ = 27, so log₃(27) = 3.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['logarithms', 'algebra'],
    grade: '11',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // Hard questions - Science
  {
    _id: generateId(),
    content: 'Which of these is NOT a part of the cell nucleus?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Chromatin', 'Nucleolus', 'Ribosome', 'Nuclear membrane'],
    correctAnswer: 'Ribosome',
    explanation: 'Ribosomes are not part of the cell nucleus. They are found in the cytoplasm and on the rough endoplasmic reticulum, where they synthesize proteins.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['biology', 'cells'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the function of ATP in cellular metabolism?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'To store genetic information',
      'To transport oxygen in the blood',
      'To store and transfer energy',
      'To catalyze protein synthesis'
    ],
    correctAnswer: 'To store and transfer energy',
    explanation: 'Adenosine triphosphate (ATP) is the primary energy carrier in cells. It stores energy in its high-energy phosphate bonds and releases it when needed for cellular processes.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['biology', 'metabolism'],
    grade: '10',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these elements has the highest electronegativity?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Sodium (Na)', 'Carbon (C)', 'Oxygen (O)', 'Fluorine (F)'],
    correctAnswer: 'Fluorine (F)',
    explanation: 'Fluorine (F) has the highest electronegativity of all elements on the periodic table, making it the most electronegative element.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['chemistry', 'periodic table'],
    grade: '10',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the function of the Krebs cycle in cellular respiration?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'To break down glucose into pyruvate',
      'To generate ATP without using oxygen',
      'To convert pyruvate into acetyl-CoA',
      'To generate NADH and FADH₂ for the electron transport chain'
    ],
    correctAnswer: 'To generate NADH and FADH₂ for the electron transport chain',
    explanation: 'The Krebs cycle (also known as the citric acid cycle or TCA cycle) is a series of chemical reactions in cellular respiration that generates NADH and FADH₂, which carry electrons to the electron transport chain for ATP production.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['biology', 'cellular respiration'],
    grade: '11',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is a correct statement about quantum mechanics?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'Electrons have fixed positions around the nucleus',
      'The position and momentum of a particle can be simultaneously determined with perfect accuracy',
      'Light can behave as both a particle and a wave',
      'Energy is always continuous, never quantized'
    ],
    correctAnswer: 'Light can behave as both a particle and a wave',
    explanation: 'Wave-particle duality is a central concept in quantum mechanics, which states that all particles exhibit both wave and particle properties. Light, for example, can behave as electromagnetic waves or as particles called photons, depending on the experimental setup.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['physics', 'quantum mechanics'],
    grade: '12',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // Hard questions - English
  {
    _id: generateId(),
    content: 'Which of these is an example of a gerund?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['to run', 'running', 'ran', 'will run'],
    correctAnswer: 'running',
    explanation: 'A gerund is a verb form that ends in "-ing" and functions as a noun. In this case, "running" can be used as a noun, as in "Running is good exercise."',
    subject: 'English',
    difficulty: DifficultyLevel.HARD,
    tags: ['grammar', 'parts of speech'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which literary device is used in the sentence: "The wind whispered through the trees"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Simile', 'Metaphor', 'Personification', 'Hyperbole'],
    correctAnswer: 'Personification',
    explanation: 'Personification is giving human qualities to non-human things. In this sentence, the wind is described as "whispering," which is a human action.',
    subject: 'English',
    difficulty: DifficultyLevel.HARD,
    tags: ['literature', 'figurative language'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these sentences contains a dangling modifier?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'The dog, wagging its tail, greeted its owner.',
      'Walking down the street, the birds were singing loudly.',
      'She read the book that was on the table.',
      'The teacher explained the problem clearly.'
    ],
    correctAnswer: 'Walking down the street, the birds were singing loudly.',
    explanation: 'A dangling modifier is a word or phrase that modifies a word not clearly stated in the sentence. In "Walking down the street, the birds were singing loudly," it sounds like the birds were walking down the street, which is illogical. The sentence should specify who was walking.',
    subject: 'English',
    difficulty: DifficultyLevel.HARD,
    tags: ['grammar', 'modifiers'],
    grade: '10',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the term for a word that is spelled the same backward and forward?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Homonym', 'Synonym', 'Palindrome', 'Antonym'],
    correctAnswer: 'Palindrome',
    explanation: 'A palindrome is a word, phrase, number, or other sequence of characters that reads the same backward as forward, such as "madam" or "racecar".',
    subject: 'English',
    difficulty: DifficultyLevel.HARD,
    tags: ['vocabulary', 'word types'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is an example of an oxymoron?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Happy birthday', 'Cold ice', 'Jumbo shrimp', 'Red rose'],
    correctAnswer: 'Jumbo shrimp',
    explanation: 'An oxymoron is a figure of speech that combines contradictory terms. "Jumbo shrimp" is an oxymoron because "jumbo" means very large, while "shrimp" implies something small.',
    subject: 'English',
    difficulty: DifficultyLevel.HARD,
    tags: ['literature', 'figurative language'],
    grade: '10',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  
  // More hard questions - Math
  {
    _id: generateId(),
    content: 'What is the value of ∫₀¹ x² dx?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['1/2', '1/3', '2/3', '1'],
    correctAnswer: '1/3',
    explanation: '∫₀¹ x² dx = [x³/3]₀¹ = 1³/3 - 0³/3 = 1/3 - 0 = 1/3.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['calculus', 'integrals'],
    grade: '12',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of the determinant of the matrix [[2, 3], [1, 4]]?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['5', '7', '8', '11'],
    correctAnswer: '5',
    explanation: 'For a 2×2 matrix [[a, b], [c, d]], the determinant is ad - bc. So for [[2, 3], [1, 4]], the determinant is 2×4 - 3×1 = 8 - 3 = 5.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['linear algebra', 'matrices'],
    grade: '11',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the limit of (sin x)/x as x approaches 0?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['0', '1', 'π', 'Undefined'],
    correctAnswer: '1',
    explanation: 'The limit of (sin x)/x as x approaches 0 is 1. This is a well-known limit in calculus that can be proven using the squeeze theorem or by using L\'Hôpital\'s rule.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['calculus', 'limits'],
    grade: '12',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the solution to the differential equation dy/dx = 2x with the initial condition y(0) = 3?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['y = x² + 3', 'y = 2x + 3', 'y = x² + 2', 'y = 2x² + 3'],
    correctAnswer: 'y = x² + 3',
    explanation: 'To solve dy/dx = 2x, we integrate both sides: y = ∫2x dx = x² + C. Using the initial condition y(0) = 3, we get 3 = 0² + C, so C = 3. Therefore, y = x² + 3.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['calculus', 'differential equations'],
    grade: '12',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the probability of getting exactly 2 heads in 5 tosses of a fair coin?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['5/32', '10/32', '15/32', '20/32'],
    correctAnswer: '10/32',
    explanation: 'Using the binomial probability formula: P(X = k) = (n choose k) × p^k × (1-p)^(n-k), where n = 5, k = 2, p = 0.5. So P(X = 2) = (5 choose 2) × 0.5² × 0.5³ = 10 × 0.25 × 0.125 = 10/32 = 5/16.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['probability', 'statistics'],
    grade: '11',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  }
];
