import { DifficultyLevel, QuestionType, Question } from '../../../types';

// Helper function to generate unique IDs
const generateId = (() => {
  let counter = 1;
  return () => (counter++).toString();
})();

// Helper function to ensure all required properties are present
const createQuestion = (q: Partial<Question>): Question => {
  return {
    _id: q._id || generateId(),
    content: q.content || '',
    type: q.type || QuestionType.MULTIPLE_CHOICE,
    subject: q.subject || '',
    topic: q.topic || q.subject || '', // Use subject as topic if not provided
    difficulty: q.difficulty || DifficultyLevel.MEDIUM,
    options: q.options || [],
    correctAnswer: q.correctAnswer || '',
    explanation: q.explanation || '',
    hints: q.hints || [], // Empty hints array
    tags: q.tags || [],
    createdBy: q.createdBy || 'system',
    createdAt: q.createdAt || new Date(),
    timeLimit: q.timeLimit,
    grade: q.grade,
    updatedAt: q.updatedAt || new Date(),
    isGenerated: q.isGenerated
  };
};

// Questions for grades 1-3
export const grade1to3Questions: Question[] = [
  // Grade 1 - Math
  {
    _id: generateId(),
    content: 'What is 2 + 3?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['4', '5', '6', '7'],
    correctAnswer: '5',
    explanation: '2 + 3 = 5. When we add 2 and 3 together, we get 5.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['addition', 'basic math'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 5 - 2?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: '5 - 2 = 3. When we subtract 2 from 5, we get 3.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['subtraction', 'basic math'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which shape has 4 equal sides?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Circle', 'Triangle', 'Square', 'Rectangle'],
    correctAnswer: 'Square',
    explanation: 'A square has 4 equal sides and 4 equal angles.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['shapes', 'geometry'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What comes after the number 9?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['8', '10', '11', '12'],
    correctAnswer: '10',
    explanation: 'The number that comes after 9 is 10.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['counting', 'number sequence'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'How many sides does a triangle have?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'A triangle has 3 sides and 3 angles.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['shapes', 'geometry'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 1 - Science
  {
    _id: generateId(),
    content: 'Which animal can fly?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Fish', 'Dog', 'Bird', 'Cat'],
    correctAnswer: 'Bird',
    explanation: 'Birds have wings that allow them to fly in the air.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['animals', 'biology'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What do plants need to grow?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Only water', 'Only sunlight', 'Water, sunlight, and air', 'Only air'],
    correctAnswer: 'Water, sunlight, and air',
    explanation: 'Plants need water, sunlight, and air to grow properly.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['plants', 'biology'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which season is usually the coldest?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Spring', 'Summer', 'Fall', 'Winter'],
    correctAnswer: 'Winter',
    explanation: 'Winter is typically the coldest season of the year.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['seasons', 'weather'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What do we use to see things?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Ears', 'Nose', 'Eyes', 'Hands'],
    correctAnswer: 'Eyes',
    explanation: 'We use our eyes to see things around us.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['human body', 'senses'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What gives us light during the day?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Moon', 'Stars', 'Sun', 'Clouds'],
    correctAnswer: 'Sun',
    explanation: 'The Sun gives us light and heat during the day.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['astronomy', 'solar system'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 1 - English
  {
    _id: generateId(),
    content: 'Which word rhymes with "cat"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Dog', 'Hat', 'Big', 'Run'],
    correctAnswer: 'Hat',
    explanation: '"Cat" and "hat" rhyme because they both end with the same sound "-at".',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['rhyming', 'phonics'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which letter comes after "D" in the alphabet?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['C', 'E', 'F', 'G'],
    correctAnswer: 'E',
    explanation: 'The letter "E" comes after "D" in the alphabet.',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['alphabet', 'letters'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which word starts with the letter "B"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Apple', 'Cat', 'Ball', 'Dog'],
    correctAnswer: 'Ball',
    explanation: 'The word "Ball" starts with the letter "B".',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['phonics', 'beginning sounds'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the opposite of "big"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Small', 'Tall', 'Wide', 'Happy'],
    correctAnswer: 'Small',
    explanation: 'The opposite (or antonym) of "big" is "small".',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['opposites', 'vocabulary'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'How many letters are in the word "dog"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
    explanation: 'The word "dog" has 3 letters: d, o, and g.',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['spelling', 'counting'],
    grade: '1',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 2 - Math
  {
    _id: generateId(),
    content: 'What is 10 + 15?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['20', '25', '30', '35'],
    correctAnswer: '25',
    explanation: '10 + 15 = 25. When we add 10 and 15 together, we get 25.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['addition', 'basic math'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 20 - 7?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['12', '13', '14', '15'],
    correctAnswer: '13',
    explanation: '20 - 7 = 13. When we subtract 7 from 20, we get 13.',
    subject: 'Math',
    difficulty: DifficultyLevel.EASY,
    tags: ['subtraction', 'basic math'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'How many sides does a hexagon have?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['4', '5', '6', '7'],
    correctAnswer: '6',
    explanation: 'A hexagon has 6 sides and 6 angles.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['shapes', 'geometry'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 5 × 2?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['7', '8', '9', '10'],
    correctAnswer: '10',
    explanation: '5 × 2 = 10. Multiplication means adding a number to itself multiple times. 5 × 2 means 5 + 5 = 10.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['multiplication', 'basic math'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'If you have 15 candies and give away 6, how many do you have left?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['7', '8', '9', '10'],
    correctAnswer: '9',
    explanation: '15 - 6 = 9. When you start with 15 candies and give away 6, you have 9 left.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['word problems', 'subtraction'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 2 - Science
  {
    _id: generateId(),
    content: 'Which of these is a living thing?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Rock', 'Water', 'Tree', 'Sun'],
    correctAnswer: 'Tree',
    explanation: 'A tree is a living thing because it grows, needs food and water, and can reproduce.',
    subject: 'Science',
    difficulty: DifficultyLevel.EASY,
    tags: ['living things', 'biology'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What do we call animals that eat only plants?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Carnivores', 'Herbivores', 'Omnivores', 'Predators'],
    correctAnswer: 'Herbivores',
    explanation: 'Animals that eat only plants are called herbivores.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['animals', 'diet'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which state of matter takes the shape of its container?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Only solids', 'Only liquids', 'Only gases', 'Both liquids and gases'],
    correctAnswer: 'Both liquids and gases',
    explanation: 'Both liquids and gases take the shape of their container. Solids maintain their own shape.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['states of matter', 'physics'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the main function of roots in a plant?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['To make food', 'To absorb water and nutrients', 'To produce flowers', 'To create seeds'],
    correctAnswer: 'To absorb water and nutrients',
    explanation: 'The main function of roots is to absorb water and nutrients from the soil for the plant.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['plants', 'biology'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which force pulls objects toward the Earth?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Magnetism', 'Electricity', 'Gravity', 'Friction'],
    correctAnswer: 'Gravity',
    explanation: 'Gravity is the force that pulls objects toward the Earth.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['forces', 'physics'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 2 - English
  {
    _id: generateId(),
    content: 'Which word is a noun?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Run', 'Happy', 'Book', 'Quickly'],
    correctAnswer: 'Book',
    explanation: 'A noun is a person, place, thing, or idea. "Book" is a thing, so it is a noun.',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['grammar', 'parts of speech'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which sentence uses correct capitalization?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['i like to read books.', 'I Like To Read Books.', 'I like to read books.', 'i Like to read Books.'],
    correctAnswer: 'I like to read books.',
    explanation: 'The first word of a sentence should be capitalized. "I" is also always capitalized.',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['capitalization', 'grammar'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which word is the plural of "child"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Childs', 'Childes', 'Children', 'Childrens'],
    correctAnswer: 'Children',
    explanation: '"Children" is the plural form of "child". It is an irregular plural that doesn\'t follow the usual rule of adding "s".',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['plurals', 'grammar'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which punctuation mark ends a question?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Period (.)', 'Question mark (?)', 'Exclamation point (!)', 'Comma (,)'],
    correctAnswer: 'Question mark (?)',
    explanation: 'A question mark (?) is used at the end of a sentence that asks a question.',
    subject: 'English',
    difficulty: DifficultyLevel.EASY,
    tags: ['punctuation', 'grammar'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the past tense of "walk"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Walking', 'Walked', 'Walks', 'Will walk'],
    correctAnswer: 'Walked',
    explanation: 'The past tense of "walk" is "walked". We add "-ed" to form the past tense of regular verbs.',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['verbs', 'tenses'],
    grade: '2',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 3 - Math
  {
    _id: generateId(),
    content: 'What is 7 × 8?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['54', '56', '58', '64'],
    correctAnswer: '56',
    explanation: '7 × 8 = 56. This is part of the multiplication table that students learn in grade 3.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['multiplication', 'arithmetic'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 42 ÷ 6?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['6', '7', '8', '9'],
    correctAnswer: '7',
    explanation: '42 ÷ 6 = 7. Division is the inverse of multiplication. Since 6 × 7 = 42, then 42 ÷ 6 = 7.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['division', 'arithmetic'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of the underlined digit in 347?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['4', '40', '400', '4,000'],
    correctAnswer: '40',
    explanation: 'In the number 347, the digit 4 is in the tens place, so its value is 4 × 10 = 40.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['place value', 'numbers'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'If a rectangle has a length of 8 cm and a width of 5 cm, what is its area?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['13 cm²', '26 cm²', '40 cm²', '80 cm²'],
    correctAnswer: '40 cm²',
    explanation: 'The area of a rectangle is calculated by multiplying length × width. So, 8 cm × 5 cm = 40 cm².',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['area', 'geometry'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What fraction of the circle is shaded if 3 out of 4 equal parts are shaded?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['1/4', '2/4', '3/4', '4/4'],
    correctAnswer: '3/4',
    explanation: 'If 3 out of 4 equal parts are shaded, then the fraction is 3/4.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['fractions', 'numbers'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 3 - Science
  {
    _id: generateId(),
    content: 'Which of these is NOT a source of light?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Sun', 'Moon', 'Lamp', 'Fire'],
    correctAnswer: 'Moon',
    explanation: 'The Moon is not a source of light. It reflects light from the Sun.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['light', 'astronomy'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the process called when a plant makes its own food using sunlight?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Respiration', 'Photosynthesis', 'Digestion', 'Reproduction'],
    correctAnswer: 'Photosynthesis',
    explanation: 'Photosynthesis is the process by which plants make their own food using sunlight, water, and carbon dioxide.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['plants', 'biology'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which animal group does a frog belong to?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Mammals', 'Reptiles', 'Amphibians', 'Fish'],
    correctAnswer: 'Amphibians',
    explanation: 'Frogs are amphibians. They start life in water (as tadpoles) and later can live on land.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['animals', 'classification'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What are the three states of matter?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Solid, water, gas', 'Solid, liquid, gas', 'Ice, water, steam', 'Hot, warm, cold'],
    correctAnswer: 'Solid, liquid, gas',
    explanation: 'The three basic states of matter are solid, liquid, and gas.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['states of matter', 'physics'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which part of a plant absorbs energy from sunlight?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Roots', 'Stem', 'Leaves', 'Flowers'],
    correctAnswer: 'Leaves',
    explanation: 'The leaves of a plant contain chlorophyll, which absorbs energy from sunlight for photosynthesis.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['plants', 'biology'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 3 - English
  {
    _id: generateId(),
    content: 'Which word is an adjective in the sentence: "The big dog barked loudly"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['The', 'big', 'dog', 'barked'],
    correctAnswer: 'big',
    explanation: 'An adjective describes a noun. In this sentence, "big" describes the noun "dog".',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['grammar', 'parts of speech'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is a complete sentence?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Running in the park.', 'The boy.', 'After school.', 'She reads books.'],
    correctAnswer: 'She reads books.',
    explanation: 'A complete sentence needs a subject and a verb. "She reads books" has both: "She" (subject) and "reads" (verb).',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['grammar', 'sentences'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the main idea of a story?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['The first sentence', 'What the story is mostly about', 'The last paragraph', 'The title only'],
    correctAnswer: 'What the story is mostly about',
    explanation: 'The main idea is what the story is mostly about - the central point or message.',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['reading comprehension', 'literature'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which word is a synonym for "happy"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Sad', 'Angry', 'Joyful', 'Tired'],
    correctAnswer: 'Joyful',
    explanation: 'Synonyms are words with similar meanings. "Joyful" means the same as "happy".',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['vocabulary', 'synonyms'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which word has the prefix "un-"?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Return', 'Unhappy', 'Careful', 'Jumping'],
    correctAnswer: 'Unhappy',
    explanation: 'The word "unhappy" has the prefix "un-", which means "not". So "unhappy" means "not happy".',
    subject: 'English',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['vocabulary', 'prefixes'],
    grade: '3',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
];
