import { DifficultyLevel, QuestionType, Question } from '../../../types';

// Helper function to generate unique IDs
const generateId = (() => {
  let counter = 200; // Start from 200 to avoid ID conflicts
  return () => (counter++).toString();
})();

// Questions for grades 7-9
export const grade7to9Questions: Question[] = [
  // Grade 7 - Math
  {
    _id: generateId(),
    content: 'Solve for x: 2(x + 3) = 16',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['5', '6', '7', '8'],
    correctAnswer: '5',
    explanation: '2(x + 3) = 16\n2x + 6 = 16\n2x = 10\nx = 5',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['algebra', 'equations'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of the expression -3² + 4 × 2?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['-1', '-9', '1', '17'],
    correctAnswer: '-1',
    explanation: '-3² + 4 × 2 = -(3²) + 4 × 2 = -9 + 8 = -1. Remember that the exponent applies only to the 3, not the negative sign.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['order of operations', 'arithmetic'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'If a shirt costs $24 and is on sale for 25% off, what is the sale price?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['$6', '$18', '$19', '$21'],
    correctAnswer: '$18',
    explanation: 'A 25% discount means the shirt costs 75% of the original price. 75% of $24 is 0.75 × $24 = $18.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['percentages', 'word problems'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the circumference of a circle with diameter 10 cm? (Use π = 3.14)',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['31.4 cm', '62.8 cm', '78.5 cm', '314 cm'],
    correctAnswer: '31.4 cm',
    explanation: 'The circumference of a circle is C = πd, where d is the diameter. So C = 3.14 × 10 cm = 31.4 cm.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['circles', 'geometry'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is equivalent to 0.125?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['1/4', '1/8', '1/10', '1/12'],
    correctAnswer: '1/8',
    explanation: '0.125 = 125/1000 = 1/8 when simplified.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['fractions', 'decimals'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 7 - Science
  {
    _id: generateId(),
    content: 'Which of these is NOT a part of the cell theory?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'All living things are made of cells',
      'Cells are the basic unit of structure and function in living things',
      'All cells contain DNA',
      'All cells come from pre-existing cells'
    ],
    correctAnswer: 'All cells contain DNA',
    explanation: 'While most cells do contain DNA, this is not part of the cell theory. Some cells, like mature red blood cells in humans, do not have a nucleus or DNA.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['biology', 'cells'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the chemical formula for water?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['H₂O', 'CO₂', 'O₂', 'NaCl'],
    correctAnswer: 'H₂O',
    explanation: 'The chemical formula for water is H₂O, which means each water molecule consists of two hydrogen atoms and one oxygen atom.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['chemistry', 'compounds'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is an example of a chemical reaction?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Boiling water', 'Dissolving salt in water', 'Melting ice', 'Rusting iron'],
    correctAnswer: 'Rusting iron',
    explanation: 'Rusting iron is a chemical reaction because it creates a new substance (iron oxide) with different properties than the original iron.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['chemistry', 'reactions'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the main function of mitochondria in a cell?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Protein synthesis', 'Energy production', 'Cell division', 'Waste removal'],
    correctAnswer: 'Energy production',
    explanation: 'Mitochondria are often called the "powerhouses" of the cell because they produce most of the cell\'s energy through cellular respiration.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['biology', 'cells'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is a correct statement about atoms?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'Atoms are the smallest unit of a compound',
      'All atoms have the same number of protons',
      'Protons have a negative charge',
      'The number of protons determines the element'
    ],
    correctAnswer: 'The number of protons determines the element',
    explanation: 'The number of protons in an atom\'s nucleus, also known as the atomic number, determines which element it is.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['chemistry', 'atoms'],
    grade: '7',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 8 - Math
  {
    _id: generateId(),
    content: 'Solve the system of equations: x + y = 5 and x - y = 3',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['x = 4, y = 1', 'x = 1, y = 4', 'x = 2, y = 3', 'x = 3, y = 2'],
    correctAnswer: 'x = 4, y = 1',
    explanation: 'From x - y = 3, we get x = 3 + y. Substituting into x + y = 5: (3 + y) + y = 5, so 3 + 2y = 5, 2y = 2, y = 1. Then x = 3 + 1 = 4.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['algebra', 'systems of equations'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the slope of the line passing through the points (2, 3) and (6, 11)?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['1', '2', '3', '4'],
    correctAnswer: '2',
    explanation: 'The slope is calculated using the formula (y₂ - y₁)/(x₂ - x₁). So, slope = (11 - 3)/(6 - 2) = 8/4 = 2.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['algebra', 'linear equations'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of x in the equation 3(x - 2) = 2(x + 1)?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['4', '5', '6', '7'],
    correctAnswer: '5',
    explanation: '3(x - 2) = 2(x + 1)\n3x - 6 = 2x + 2\n3x - 2x = 2 + 6\nx = 8',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['algebra', 'equations'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the Pythagorean theorem?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['a² + b² = c²', 'a + b = c', 'a × b = c', '(a + b)² = c²'],
    correctAnswer: 'a² + b² = c²',
    explanation: 'The Pythagorean theorem states that in a right triangle, the square of the length of the hypotenuse (c) equals the sum of the squares of the lengths of the other two sides (a and b).',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['geometry', 'triangles'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Simplify the expression: 2(3x - 4) + 5x',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['6x - 8 + 5x', '11x - 8', '11x - 4', '6x + 5x - 4'],
    correctAnswer: '11x - 8',
    explanation: '2(3x - 4) + 5x = 6x - 8 + 5x = 11x - 8',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['algebra', 'expressions'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 8 - Science
  {
    _id: generateId(),
    content: 'Which of these best describes Newton\'s First Law of Motion?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'Force equals mass times acceleration',
      'For every action, there is an equal and opposite reaction',
      'An object at rest stays at rest unless acted upon by an external force',
      'Energy cannot be created or destroyed'
    ],
    correctAnswer: 'An object at rest stays at rest unless acted upon by an external force',
    explanation: 'Newton\'s First Law of Motion, also known as the Law of Inertia, states that an object at rest stays at rest and an object in motion stays in motion with the same speed and direction unless acted upon by an external force.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['physics', 'motion'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the pH of a neutral solution?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['0', '7', '10', '14'],
    correctAnswer: '7',
    explanation: 'A neutral solution has a pH of 7. Solutions with a pH less than 7 are acidic, and solutions with a pH greater than 7 are basic (alkaline).',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['chemistry', 'pH'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is NOT a form of energy?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Kinetic energy', 'Potential energy', 'Thermal energy', 'Mass energy'],
    correctAnswer: 'Mass energy',
    explanation: '"Mass energy" is not a standard form of energy. Common forms include kinetic, potential, thermal, electrical, chemical, nuclear, and electromagnetic energy.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['physics', 'energy'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the main function of DNA in cells?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'Energy production',
      'Protein synthesis',
      'Storing genetic information',
      'Cell division'
    ],
    correctAnswer: 'Storing genetic information',
    explanation: 'DNA (deoxyribonucleic acid) stores genetic information that serves as instructions for the development, functioning, growth, and reproduction of all known organisms.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['biology', 'genetics'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is an example of a physical property?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Flammability', 'Reactivity with acid', 'Melting point', 'Ability to rust'],
    correctAnswer: 'Melting point',
    explanation: 'Melting point is a physical property because it describes a physical change (solid to liquid) and can be observed without changing the chemical composition of the substance.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['chemistry', 'properties of matter'],
    grade: '8',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 9 - Math
  {
    _id: generateId(),
    content: 'Factor the expression: x² - 9',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['(x - 3)(x + 3)', '(x - 9)(x + 1)', '(x - 3)²', '(x + 3)²'],
    correctAnswer: '(x - 3)(x + 3)',
    explanation: 'x² - 9 is a difference of squares: a² - b² = (a - b)(a + b). Here, a = x and b = 3, so x² - 9 = (x - 3)(x + 3).',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['algebra', 'factoring'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Solve the quadratic equation: x² - 5x + 6 = 0',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['x = 2, x = 3', 'x = -2, x = -3', 'x = 2, x = -3', 'x = -2, x = 3'],
    correctAnswer: 'x = 2, x = 3',
    explanation: 'To solve x² - 5x + 6 = 0, we can factor: (x - 2)(x - 3) = 0. So either x - 2 = 0 or x - 3 = 0, which gives us x = 2 or x = 3.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['algebra', 'quadratic equations'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the equation of a line with slope 2 that passes through the point (3, 4)?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['y = 2x - 2', 'y = 2x - 1', 'y = 2x', 'y = 2x + 1'],
    correctAnswer: 'y = 2x - 2',
    explanation: 'Using the point-slope form: y - y₁ = m(x - x₁), we get y - 4 = 2(x - 3), which simplifies to y - 4 = 2x - 6, or y = 2x - 2.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['algebra', 'linear equations'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the value of the discriminant for the quadratic equation 2x² - 4x + 3 = 0?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['-8', '-4', '4', '8'],
    correctAnswer: '-8',
    explanation: 'The discriminant is b² - 4ac. For 2x² - 4x + 3 = 0, a = 2, b = -4, and c = 3. So the discriminant is (-4)² - 4(2)(3) = 16 - 24 = -8.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['algebra', 'quadratic equations'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'If f(x) = 3x - 2, what is f(4)?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['8', '10', '12', '14'],
    correctAnswer: '10',
    explanation: 'To find f(4), substitute x = 4 into the function: f(4) = 3(4) - 2 = 12 - 2 = 10.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['algebra', 'functions'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 9 - Science
  {
    _id: generateId(),
    content: 'Which of these is the correct formula for calculating speed?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Speed = Distance × Time', 'Speed = Distance ÷ Time', 'Speed = Time ÷ Distance', 'Speed = Force ÷ Mass'],
    correctAnswer: 'Speed = Distance ÷ Time',
    explanation: 'Speed is calculated by dividing the distance traveled by the time taken: Speed = Distance ÷ Time.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['physics', 'motion'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the chemical symbol for gold?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Go', 'Gd', 'Au', 'Ag'],
    correctAnswer: 'Au',
    explanation: 'The chemical symbol for gold is Au, which comes from the Latin word "aurum" meaning gold.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['chemistry', 'elements'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is NOT a part of the cell nucleus?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Chromatin', 'Nucleolus', 'Ribosome', 'Nuclear membrane'],
    correctAnswer: 'Ribosome',
    explanation: 'Ribosomes are not part of the cell nucleus. They are found in the cytoplasm and on the rough endoplasmic reticulum, where they synthesize proteins.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['biology', 'cells'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the main function of the ozone layer?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'To trap heat in the atmosphere',
      'To protect Earth from harmful UV radiation',
      'To produce oxygen for living organisms',
      'To regulate Earth\'s temperature'
    ],
    correctAnswer: 'To protect Earth from harmful UV radiation',
    explanation: 'The ozone layer in the stratosphere absorbs most of the Sun\'s ultraviolet (UV) radiation, protecting living organisms on Earth from its harmful effects.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['earth science', 'atmosphere'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is an example of a chemical bond?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Gravity', 'Magnetism', 'Covalent bond', 'Friction'],
    correctAnswer: 'Covalent bond',
    explanation: 'A covalent bond is a type of chemical bond where atoms share electron pairs to achieve a more stable electron configuration.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['chemistry', 'bonding'],
    grade: '9',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
];
