import { DifficultyLevel, QuestionType, Question } from '../../../types';

// Helper function to generate unique IDs
const generateId = (() => {
  let counter = 100; // Start from 100 to avoid ID conflicts
  return () => (counter++).toString();
})();

// Questions for grades 4-6
export const grade4to6Questions: Question[] = [
  // Grade 4 - Math
  {
    _id: generateId(),
    content: 'What is 24 × 6?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['124', '144', '154', '164'],
    correctAnswer: '144',
    explanation: '24 × 6 = 144. You can calculate this by multiplying 24 by 6.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['multiplication', 'arithmetic'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 125 ÷ 5?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['15', '20', '25', '30'],
    correctAnswer: '25',
    explanation: '125 ÷ 5 = 25. Division is the inverse of multiplication. Since 5 × 25 = 125, then 125 ÷ 5 = 25.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['division', 'arithmetic'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which fraction is equivalent to 1/2?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['2/5', '3/6', '2/6', '1/3'],
    correctAnswer: '3/6',
    explanation: '3/6 = 1/2 because if you divide both the numerator and denominator by 3, you get 1/2.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['fractions', 'equivalence'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the perimeter of a rectangle with length 8 cm and width 5 cm?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['13 cm', '26 cm', '40 cm', '80 cm'],
    correctAnswer: '26 cm',
    explanation: 'The perimeter of a rectangle is calculated by 2 × (length + width). So, 2 × (8 cm + 5 cm) = 2 × 13 cm = 26 cm.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['perimeter', 'geometry'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 3/4 of 20?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['12', '15', '16', '18'],
    correctAnswer: '15',
    explanation: 'To find 3/4 of 20, multiply 20 by 3/4: 20 × 3/4 = 60/4 = 15.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['fractions', 'multiplication'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 4 - Science
  {
    _id: generateId(),
    content: 'Which of these is a renewable resource?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Coal', 'Natural gas', 'Solar energy', 'Petroleum'],
    correctAnswer: 'Solar energy',
    explanation: 'Solar energy is a renewable resource because it comes from the sun, which will continue to provide energy for billions of years.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['resources', 'environment'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the main function of the lungs in the human body?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Pump blood', 'Filter waste', 'Exchange gases', 'Digest food'],
    correctAnswer: 'Exchange gases',
    explanation: 'The main function of the lungs is to exchange gases - taking in oxygen and releasing carbon dioxide.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['human body', 'respiratory system'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is an example of a physical change?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Burning wood', 'Rusting iron', 'Melting ice', 'Cooking an egg'],
    correctAnswer: 'Melting ice',
    explanation: 'Melting ice is a physical change because the water only changes state from solid to liquid; it doesn\'t change its chemical composition.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['matter', 'physical changes'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What causes day and night on Earth?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['The Earth orbiting the Sun', 'The Earth rotating on its axis', 'The Moon blocking the Sun', 'The Sun moving around the Earth'],
    correctAnswer: 'The Earth rotating on its axis',
    explanation: 'Day and night are caused by the Earth rotating on its axis. The side facing the Sun experiences day, while the side facing away experiences night.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['astronomy', 'Earth'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these animals is a vertebrate?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Jellyfish', 'Butterfly', 'Frog', 'Spider'],
    correctAnswer: 'Frog',
    explanation: 'A frog is a vertebrate because it has a backbone. Jellyfish, butterflies, and spiders are invertebrates.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['animals', 'classification'],
    grade: '4',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 5 - Math
  {
    _id: generateId(),
    content: 'What is the value of 3² + 4²?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['7', '25', '49', '81'],
    correctAnswer: '25',
    explanation: '3² + 4² = 9 + 16 = 25. The exponent 2 means to square the number (multiply it by itself).',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['exponents', 'arithmetic'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 2.5 × 0.4?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['0.1', '0.625', '1', '10'],
    correctAnswer: '1',
    explanation: '2.5 × 0.4 = 1. When multiplying decimals, multiply as with whole numbers, then count the total number of decimal places in both factors to determine the decimal places in the product.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['decimals', 'multiplication'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these fractions is the largest?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['3/8', '1/2', '2/5', '3/7'],
    correctAnswer: '1/2',
    explanation: 'To compare fractions, we can convert them to decimals: 3/8 = 0.375, 1/2 = 0.5, 2/5 = 0.4, 3/7 ≈ 0.429. So 1/2 is the largest.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['fractions', 'comparison'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the volume of a rectangular prism with length 4 cm, width 3 cm, and height 5 cm?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['12 cm³', '24 cm³', '60 cm³', '120 cm³'],
    correctAnswer: '60 cm³',
    explanation: 'The volume of a rectangular prism is calculated by multiplying length × width × height. So, 4 cm × 3 cm × 5 cm = 60 cm³.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['volume', 'geometry'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'If a recipe calls for 3/4 cup of flour to make 12 cookies, how much flour is needed to make 18 cookies?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['1 cup', '1 1/8 cups', '1 1/4 cups', '1 1/2 cups'],
    correctAnswer: '1 1/8 cups',
    explanation: 'If 12 cookies need 3/4 cup, then 18 cookies need (18 ÷ 12) × 3/4 = 1.5 × 3/4 = 9/8 = 1 1/8 cups.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['proportions', 'fractions'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 5 - Science
  {
    _id: generateId(),
    content: 'Which of these is NOT a compound?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Water (H₂O)', 'Carbon dioxide (CO₂)', 'Oxygen (O₂)', 'Salt (NaCl)'],
    correctAnswer: 'Oxygen (O₂)',
    explanation: 'Oxygen (O₂) is not a compound; it\'s an element. A compound contains atoms of different elements, while O₂ contains only oxygen atoms.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['chemistry', 'elements'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the main function of the heart in the human body?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Filter blood', 'Pump blood', 'Produce blood cells', 'Remove carbon dioxide'],
    correctAnswer: 'Pump blood',
    explanation: 'The main function of the heart is to pump blood throughout the body, delivering oxygen and nutrients to cells and removing waste products.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['human body', 'circulatory system'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is an example of a chemical change?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Dissolving sugar in water', 'Freezing water', 'Cutting paper', 'Burning wood'],
    correctAnswer: 'Burning wood',
    explanation: 'Burning wood is a chemical change because it creates new substances (ash, gases) with different properties than the original wood.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['chemistry', 'chemical changes'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What causes the seasons on Earth?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['The Earth\'s distance from the Sun', 'The Earth\'s tilt on its axis', 'The Moon\'s gravity', 'The Earth\'s rotation speed'],
    correctAnswer: 'The Earth\'s tilt on its axis',
    explanation: 'Seasons are caused by the Earth\'s tilt on its axis as it orbits the Sun, which changes the angle at which sunlight hits different parts of Earth throughout the year.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['astronomy', 'Earth'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is a characteristic of all living things?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['They can fly', 'They have cells', 'They have leaves', 'They can swim'],
    correctAnswer: 'They have cells',
    explanation: 'All living things are made up of cells, which are the basic units of life.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['biology', 'cells'],
    grade: '5',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 6 - Math
  {
    _id: generateId(),
    content: 'What is the value of x in the equation 3x + 7 = 22?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['3', '5', '7', '15'],
    correctAnswer: '5',
    explanation: 'To solve for x: 3x + 7 = 22, subtract 7 from both sides: 3x = 15, then divide both sides by 3: x = 5.',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['algebra', 'equations'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is 30% of 80?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['21', '24', '27', '30'],
    correctAnswer: '24',
    explanation: 'To find 30% of 80, multiply 80 by 0.30: 80 × 0.30 = 24.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['percentages', 'arithmetic'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the ratio of 15 to 25 in simplest form?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['3:5', '5:3', '15:25', '25:15'],
    correctAnswer: '3:5',
    explanation: 'The ratio 15:25 can be simplified by dividing both numbers by their greatest common factor, which is 5. So, 15:25 = 3:5.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['ratios', 'simplification'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the area of a circle with radius 6 cm? (Use π = 3.14)',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['36π cm²', '12π cm²', '18π cm²', '24π cm²'],
    correctAnswer: '36π cm²',
    explanation: 'The area of a circle is calculated using the formula A = πr². So, A = π × 6² = π × 36 = 36π cm². Using π = 3.14, this is approximately 113.04 cm².',
    subject: 'Math',
    difficulty: DifficultyLevel.HARD,
    tags: ['area', 'circles'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'If a car travels at 60 miles per hour, how far will it travel in 2.5 hours?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['120 miles', '150 miles', '180 miles', '200 miles'],
    correctAnswer: '150 miles',
    explanation: 'Distance = Speed × Time. So, Distance = 60 miles per hour × 2.5 hours = 150 miles.',
    subject: 'Math',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['word problems', 'rate'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },

  // Grade 6 - Science
  {
    _id: generateId(),
    content: 'Which of these is the correct order of the planets from the Sun?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: [
      'Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune',
      'Mercury, Venus, Earth, Mars, Saturn, Jupiter, Uranus, Neptune',
      'Mercury, Earth, Venus, Mars, Jupiter, Saturn, Uranus, Neptune',
      'Mercury, Venus, Earth, Mars, Jupiter, Saturn, Neptune, Uranus'
    ],
    correctAnswer: 'Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune',
    explanation: 'The correct order of the planets from the Sun is: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['astronomy', 'solar system'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the process by which plants lose water vapor through their leaves called?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Photosynthesis', 'Respiration', 'Transpiration', 'Condensation'],
    correctAnswer: 'Transpiration',
    explanation: 'Transpiration is the process by which plants lose water vapor through small openings in their leaves called stomata.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['plants', 'biology'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is NOT a type of simple machine?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Lever', 'Pulley', 'Battery', 'Inclined plane'],
    correctAnswer: 'Battery',
    explanation: 'A battery is not a simple machine. The six types of simple machines are: lever, pulley, wheel and axle, inclined plane, wedge, and screw.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['physics', 'simple machines'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'What is the main function of red blood cells in the human body?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['Fight infection', 'Carry oxygen', 'Clot blood', 'Produce antibodies'],
    correctAnswer: 'Carry oxygen',
    explanation: 'The main function of red blood cells is to carry oxygen from the lungs to the body\'s tissues and organs.',
    subject: 'Science',
    difficulty: DifficultyLevel.MEDIUM,
    tags: ['human body', 'blood'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: generateId(),
    content: 'Which of these is an example of potential energy?',
    type: QuestionType.MULTIPLE_CHOICE,
    options: ['A car driving on a highway', 'A person running', 'A book sitting on a high shelf', 'A ball rolling down a hill'],
    correctAnswer: 'A book sitting on a high shelf',
    explanation: 'A book sitting on a high shelf has potential energy due to its position. Potential energy is stored energy that has the potential to do work.',
    subject: 'Science',
    difficulty: DifficultyLevel.HARD,
    tags: ['physics', 'energy'],
    grade: '6',
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
];
