import { Question, DifficultyLevel, QuestionType } from '../types';
import { ReadingPassage } from './readingPassagesDatabase';

/**
 * Final Reading Passages to Reach 200+ Questions Target
 * Comprehensive passages with 6 questions each across all grades
 */

export const finalReadingPassages: ReadingPassage[] = [
  
  // COMPREHENSIVE PASSAGES WITH 6 QUESTIONS EACH
  {
    id: 'g3_medium_final_1',
    title: 'The Amazing Honeybee Colony',
    passage: `A honeybee colony is like a busy city with thousands of workers, each with an important job. The queen bee is the most important bee in the hive. She lays up to 2,000 eggs every day! Worker bees are all female and do many different jobs. Some worker bees are nurses who take care of baby bees. Others are builders who make the honeycomb from wax. Guard bees protect the hive from enemies. Forager bees fly out to find flowers and bring back nectar and pollen. When a forager bee finds good flowers, she does a special dance to tell other bees where to go. The dance shows the direction and distance to the flowers. Male bees are called drones, and their only job is to mate with queens from other hives. In winter, the bees cluster together to stay warm and eat the honey they stored during summer. A healthy hive can have 50,000 to 80,000 bees working together!`,
    grade: '3',
    difficulty: DifficultyLevel.MEDIUM,
    genre: 'science',
    wordCount: 168,
    readingLevel: 'developing_reader',
    questions: [
      {
        _id: 'g3_medium_final_1_q1',
        content: 'How many eggs can a queen bee lay per day?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['Up to 2,000', 'Up to 1,000', 'Up to 500', 'Up to 100'],
        correctAnswer: 'Up to 2,000',
        explanation: 'The passage states "She lays up to 2,000 eggs every day!"',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.MEDIUM,
        grade: '3',
        tags: ['science', 'insects', 'numbers'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g3_medium_final_1_q2',
        content: 'What do nurse bees do?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['Take care of baby bees', 'Build honeycomb', 'Guard the hive', 'Find flowers'],
        correctAnswer: 'Take care of baby bees',
        explanation: 'The passage explains "Some worker bees are nurses who take care of baby bees."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.MEDIUM,
        grade: '3',
        tags: ['science', 'jobs', 'care'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g3_medium_final_1_q3',
        content: 'How do forager bees tell others about good flowers?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['They do a special dance', 'They make buzzing sounds', 'They leave a scent trail', 'They bring back samples'],
        correctAnswer: 'They do a special dance',
        explanation: 'The passage states "she does a special dance to tell other bees where to go."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.MEDIUM,
        grade: '3',
        tags: ['science', 'communication', 'behavior'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g3_medium_final_1_q4',
        content: 'What are male bees called?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['Drones', 'Workers', 'Guards', 'Builders'],
        correctAnswer: 'Drones',
        explanation: 'The passage states "Male bees are called drones."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.MEDIUM,
        grade: '3',
        tags: ['science', 'vocabulary', 'types'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g3_medium_final_1_q5',
        content: 'What do bees do in winter?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['Cluster together to stay warm and eat stored honey', 'Fly south to warmer places', 'Sleep until spring', 'Build new hives'],
        correctAnswer: 'Cluster together to stay warm and eat stored honey',
        explanation: 'The passage explains "In winter, the bees cluster together to stay warm and eat the honey they stored during summer."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.MEDIUM,
        grade: '3',
        tags: ['science', 'seasons', 'survival'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g3_medium_final_1_q6',
        content: 'How many bees can be in a healthy hive?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['50,000 to 80,000', '5,000 to 8,000', '500 to 800', '5 to 8'],
        correctAnswer: '50,000 to 80,000',
        explanation: 'The passage concludes "A healthy hive can have 50,000 to 80,000 bees working together!"',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.MEDIUM,
        grade: '3',
        tags: ['science', 'numbers', 'colony size'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ]
  },

  {
    id: 'g5_hard_final_1',
    title: 'The Mystery of Dark Matter',
    passage: `Scientists believe that about 85% of all matter in the universe is made of something called dark matter, yet we cannot see it or touch it. This invisible substance doesn't emit, absorb, or reflect light, which is why it's called "dark." We only know it exists because of its gravitational effects on visible matter like stars and galaxies. Imagine trying to understand a dance by watching only some of the dancers—that's what astronomers face when studying the universe. They can see stars and galaxies moving in ways that suggest there's much more matter present than what they can observe. Dark matter acts like invisible scaffolding that holds the universe together. Without it, galaxies would fly apart because there wouldn't be enough gravity to keep them intact. Scientists have built special detectors deep underground to try to catch dark matter particles, but so far, these mysterious particles have remained elusive. Some theories suggest dark matter is made of exotic particles that rarely interact with ordinary matter. Understanding dark matter is one of the biggest challenges in modern physics, and solving this mystery could revolutionize our understanding of the universe.`,
    grade: '5',
    difficulty: DifficultyLevel.HARD,
    genre: 'science',
    wordCount: 198,
    readingLevel: 'advanced_reader',
    questions: [
      {
        _id: 'g5_hard_final_1_q1',
        content: 'What percentage of all matter in the universe is dark matter?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['About 85%', 'About 50%', 'About 25%', 'About 15%'],
        correctAnswer: 'About 85%',
        explanation: 'The passage begins "Scientists believe that about 85% of all matter in the universe is made of something called dark matter."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '5',
        tags: ['science', 'astronomy', 'statistics'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g5_hard_final_1_q2',
        content: 'Why is it called "dark" matter?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['It doesn\'t emit, absorb, or reflect light', 'It\'s black in color', 'It only exists at night', 'It\'s found in dark places'],
        correctAnswer: 'It doesn\'t emit, absorb, or reflect light',
        explanation: 'The passage explains "This invisible substance doesn\'t emit, absorb, or reflect light, which is why it\'s called \'dark.\'"',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '5',
        tags: ['science', 'properties', 'light'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g5_hard_final_1_q3',
        content: 'How do we know dark matter exists?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['Through its gravitational effects on visible matter', 'We can see it with telescopes', 'It glows in the dark', 'It makes sounds in space'],
        correctAnswer: 'Through its gravitational effects on visible matter',
        explanation: 'The passage states "We only know it exists because of its gravitational effects on visible matter like stars and galaxies."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '5',
        tags: ['science', 'evidence', 'gravity'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g5_hard_final_1_q4',
        content: 'What analogy does the passage use to describe astronomers\' challenge?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['Trying to understand a dance by watching only some dancers', 'Looking for a needle in a haystack', 'Reading a book with missing pages', 'Solving a puzzle with missing pieces'],
        correctAnswer: 'Trying to understand a dance by watching only some dancers',
        explanation: 'The passage uses this analogy: "Imagine trying to understand a dance by watching only some of the dancers—that\'s what astronomers face when studying the universe."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '5',
        tags: ['science', 'analogy', 'comparison'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g5_hard_final_1_q5',
        content: 'What would happen to galaxies without dark matter?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['They would fly apart', 'They would get bigger', 'They would turn black', 'They would move faster'],
        correctAnswer: 'They would fly apart',
        explanation: 'The passage explains "Without it, galaxies would fly apart because there wouldn\'t be enough gravity to keep them intact."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '5',
        tags: ['science', 'consequences', 'gravity'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g5_hard_final_1_q6',
        content: 'Where have scientists built detectors to try to find dark matter?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['Deep underground', 'In space stations', 'On mountain tops', 'In the ocean'],
        correctAnswer: 'Deep underground',
        explanation: 'The passage states "Scientists have built special detectors deep underground to try to catch dark matter particles."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '5',
        tags: ['science', 'research', 'location'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ]
  },

  {
    id: 'g7_hard_final_1',
    title: 'The Art and Science of Forensic Investigation',
    passage: `Forensic science combines scientific methods with detective work to solve crimes and legal disputes. This fascinating field uses everything from DNA analysis to fingerprint comparison, ballistics testing to digital forensics. When investigators arrive at a crime scene, they must carefully document and collect evidence while avoiding contamination that could compromise their findings. Every piece of evidence tells a story, but forensic scientists must be meticulous in their analysis to ensure accuracy. DNA evidence has revolutionized criminal investigations since its introduction in the 1980s. A single hair, drop of blood, or skin cell can provide enough genetic material to identify a suspect or exclude an innocent person. However, DNA evidence isn't infallible—contamination, degradation, or misinterpretation can lead to errors. Fingerprint analysis, one of the oldest forensic techniques, relies on the fact that no two people have identical fingerprints. Digital forensics has become increasingly important as criminals use technology in their activities. Experts can recover deleted files, trace internet activity, and analyze metadata to build cases. Despite advances in forensic science, investigators must remember that evidence interpretation requires human judgment, and mistakes can have serious consequences for justice.`,
    grade: '7',
    difficulty: DifficultyLevel.HARD,
    genre: 'science',
    wordCount: 208,
    readingLevel: 'advanced_reader',
    questions: [
      {
        _id: 'g7_hard_final_1_q1',
        content: 'What does forensic science combine?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['Scientific methods with detective work', 'Art with mathematics', 'History with geography', 'Medicine with law'],
        correctAnswer: 'Scientific methods with detective work',
        explanation: 'The passage begins "Forensic science combines scientific methods with detective work to solve crimes and legal disputes."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '7',
        tags: ['science', 'forensics', 'definition'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g7_hard_final_1_q2',
        content: 'When was DNA evidence introduced to criminal investigations?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['The 1980s', 'The 1970s', 'The 1990s', 'The 2000s'],
        correctAnswer: 'The 1980s',
        explanation: 'The passage states "DNA evidence has revolutionized criminal investigations since its introduction in the 1980s."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '7',
        tags: ['science', 'history', 'DNA'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g7_hard_final_1_q3',
        content: 'What makes fingerprint analysis reliable?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['No two people have identical fingerprints', 'Fingerprints never change', 'Fingerprints are easy to collect', 'Everyone has fingerprints'],
        correctAnswer: 'No two people have identical fingerprints',
        explanation: 'The passage explains "Fingerprint analysis, one of the oldest forensic techniques, relies on the fact that no two people have identical fingerprints."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '7',
        tags: ['science', 'fingerprints', 'uniqueness'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g7_hard_final_1_q4',
        content: 'What can cause errors in DNA evidence?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['Contamination, degradation, or misinterpretation', 'Only contamination', 'Only degradation', 'Only misinterpretation'],
        correctAnswer: 'Contamination, degradation, or misinterpretation',
        explanation: 'The passage states "However, DNA evidence isn\'t infallible—contamination, degradation, or misinterpretation can lead to errors."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '7',
        tags: ['science', 'errors', 'DNA'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g7_hard_final_1_q5',
        content: 'Why has digital forensics become increasingly important?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['Criminals use technology in their activities', 'Computers are getting cheaper', 'Everyone has smartphones', 'Digital evidence is always accurate'],
        correctAnswer: 'Criminals use technology in their activities',
        explanation: 'The passage explains "Digital forensics has become increasingly important as criminals use technology in their activities."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '7',
        tags: ['science', 'technology', 'crime'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        _id: 'g7_hard_final_1_q6',
        content: 'What important point does the passage make about evidence interpretation?',
        type: QuestionType.MULTIPLE_CHOICE,
        options: ['It requires human judgment and mistakes can have serious consequences', 'It\'s always completely accurate', 'Computers do all the interpretation', 'It\'s simple and straightforward'],
        correctAnswer: 'It requires human judgment and mistakes can have serious consequences',
        explanation: 'The passage concludes "evidence interpretation requires human judgment, and mistakes can have serious consequences for justice."',
        subject: 'Reading',
        topic: 'Reading Comprehension',
        difficulty: DifficultyLevel.HARD,
        grade: '7',
        tags: ['science', 'judgment', 'consequences'],
        createdBy: 'final-system',
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ]
  }
];

export default finalReadingPassages;
