version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: testace-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: testace
    volumes:
      - mongodb_data:/data/db
    networks:
      - testace-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: testace-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/testace?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - testace-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: testace-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_SERVER_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - testace-network

  nginx:
    image: nginx:alpine
    container_name: testace-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - testace-network

volumes:
  mongodb_data:

networks:
  testace-network:
    driver: bridge
